statusBits = {}
statusBits['pumpUp'] = 1 << 0
statusBits['pumpDown'] = 1 << 1
statusBits['control'] = 1 << 2
statusBits['venting'] = 1 << 3
statusBits['stable'] = 1 << 4
statusBits['vented'] = 1 << 5
statusBits['excessLeak'] = 1 << 6
statusBits['excessVolume'] = 1 << 7
statusBits['overPressure'] = 1 << 8
statusBits['additional'] = 1 << 9
statusBits['excessOffset'] = 1 << 10
statusBits['measure'] = 1 << 11
statusBits['fineControl'] = 1 << 12
statusBits['pistonCentered'] = 1 << 13
statusBits['centering'] = 1 << 14
statusBits['controlledVent'] = 1 << 15
statusBits['centeringVent'] = 1 << 16
statusBits['rangeExceeded'] = 1 << 17
statusBits['coarseControlError'] = 1 << 18
statusBits['ventDirUp'] = 1 << 19
statusBits['ventDirDown'] = 1 << 20
statusBits['controlRate'] = 1 << 21
statusBits['maxLim'] = 1 << 22
statusBits['minLim'] = 1 << 23
statusBits['fastVent'] = 1 << 24
statusBits['reserved8'] = 1 << 25
statusBits['reserved7'] = 1 << 26
statusBits['reserved6'] = 1 << 27
statusBits['reserved5'] = 1 << 28
statusBits['reserved4'] = 1 << 29
statusBits['reserved3'] = 1 << 30
statusBits['reserved2'] = 1 << 31
statusBits['reserved1'] = 1 << 32

stepCheck = {}
stepCheck['one'] = 1 << 0
stepCheck['two'] = 1 << 1
stepCheck['three'] = 1 << 2
stepCheck['four'] = 1 << 3
stepCheck['five'] = 1 << 4
stepCheck['six'] = 1 << 5
stepCheck['seven'] = 1 << 6
stepCheck['eight'] = 1 << 7
stepCheck['nine'] = 1 << 8
stepCheck['ten'] = 1 << 9
stepCheck['eleven'] = 1 << 10
stepCheck['twelve'] = 1 << 11
stepCheck['thirteen'] = 1 << 12
stepCheck['fourteen'] = 1 << 13
stepCheck['fifteen'] = 1 << 14
stepCheck['sixteen'] = 1 << 15

testFailedTimeout = 10


